name: CI
on:
  pull_request:
env:
  SCALAC_FATAL_WARNINGS: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v10
        with:
         java-version: adopt@1.11
      - name: scalafmt
        run: sbt scalafmtCheck
      - name: test
        run: sbt '+test'
      - name: docs
        run: sbt 'docs/mdoc'
